name: hello-world

# will trigger on push to repo
on: 
  #push
  workflow_dispatch:  # Only runs manually

jobs:
  hello-world-job:
  
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - run: echo "$(cat src/big-picture/hello_world.txt)"
